for online deberta env

diff --git a/xpu-graph/npu-for-deberta-x86_64/Dockerfile.runtime b/xpu-graph/npu-for-deberta-x86_64/Dockerfile.runtime
--- a/xpu-graph/npu-for-deberta-x86_64/Dockerfile.runtime
+++ b/xpu-graph/npu-for-deberta-x86_64/Dockerfile.runtime
@@ -19,106 +19,101 @@ ENV HTTP_PROXY=${http_proxy} \
     HTTPS_PROXY=${http_proxy} \
     FTP_PROXY=${http_proxy}
 
-RUN apt-get update && \
-    apt-get install -y apt-utils adduser sudo vim  tmux openssh-server net-tools iputils-ping software-properties-common && \
-    apt-get install -y python3-dbg libmpich-dev \
-    git python3-distutils python3-wheel python3-yaml python3-setuptools \
-    libssl-dev ninja-build libzstd-dev \
-    wget tree bash-completion curl sshpass locales \
-    ninja-build ccache libssl-dev build-essential \
-    libbz2-dev libssl-dev libffi-dev \
-    # for build gcc
-    bison flex texinfo gperf libtool patchutils bc zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev libisl-dev autoconf automake libncurses5-dev libelf-dev \
-    # for spack3
-    libffi-dev libsqlite3-dev build-essential zlib1g-dev libssl-dev zip unzip \
-    locales gcc cmake rinetd libtcmalloc-minimal4 graphviz git sudo zsh \
-    libcurl4-openssl-dev libsecret-1-0 \
-        > /dev/null && \
-    apt-get clean && apt-get purge && rm -rf /var/lib/apt/lists && \
-    locale-gen en_US.UTF-8 && \
-    mkdir -p /var/run/sshd && \
-    echo "if [ -f /etc/bash_completion.d/git ]; then\n\
-    . /etc/bash_completion.d/git\n\
-fi\n\
-" >> /etc/profile
+# RUN apt-get update && \
+#     apt-get install -y apt-utils adduser sudo vim  tmux openssh-server net-tools iputils-ping software-properties-common && \
+#     apt-get install -y python3-dbg libmpich-dev \
+#     git python3-distutils python3-wheel python3-yaml python3-setuptools \
+#     libssl-dev ninja-build libzstd-dev \
+#     wget tree bash-completion curl sshpass locales \
+#     ninja-build ccache libssl-dev build-essential \
+#     libbz2-dev libssl-dev libffi-dev \
+#     # for build gcc
+#     bison flex texinfo gperf libtool patchutils bc zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev libisl-dev autoconf automake libncurses5-dev libelf-dev \
+#     # for spack3
+#     libffi-dev libsqlite3-dev build-essential zlib1g-dev libssl-dev zip unzip \
+#     locales gcc cmake rinetd libtcmalloc-minimal4 graphviz git sudo zsh \
+#     libcurl4-openssl-dev libsecret-1-0 \
+#         > /dev/null && \
+#     apt-get clean && apt-get purge && rm -rf /var/lib/apt/lists && \
+#     locale-gen en_US.UTF-8 && \
+#     mkdir -p /var/run/sshd && \
+#     echo "if [ -f /etc/bash_completion.d/git ]; then\n\
+#     . /etc/bash_completion.d/git\n\
+# fi\n\
+# " >> /etc/profile
 # config language
-ENV LANG=C.UTF-8
+# ENV LANG=C.UTF-8
 
-# install gcc
-RUN mkdir -p /tmp/gcc/ && cd /tmp/gcc/ && \
-    wget https://ftp.gnu.org/gnu/gcc/gcc-9.5.0/gcc-9.5.0.tar.gz && \
-    tar xvf gcc-9.5.0.tar.gz && \
-    cd gcc-9.5.0 && \
-    mkdir build && cd build && \
-    ../configure --prefix=/usr/local/gcc-9.5.0 --enable-languages=c,c++ --disable-multilib && \
-    make -j$(nproc) && \
-    make install && \
-    rm -rf /tmp/gcc/ && \
-    update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-9.5.0/bin/gcc 60 && \
-    update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-9.5.0/bin/g++ 60 && \
-    update-alternatives --config gcc && \
-    update-alternatives --config g++
+# # install gcc
+# RUN mkdir -p /tmp/gcc/ && cd /tmp/gcc/ && \
+#     wget https://ftp.gnu.org/gnu/gcc/gcc-9.5.0/gcc-9.5.0.tar.gz && \
+#     tar xvf gcc-9.5.0.tar.gz && \
+#     cd gcc-9.5.0 && \
+#     mkdir build && cd build && \
+#     ../configure --prefix=/usr/local/gcc-9.5.0 --enable-languages=c,c++ --disable-multilib && \
+#     make -j$(nproc) && \
+#     make install && \
+#     rm -rf /tmp/gcc/ && \
+#     update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc-9.5.0/bin/gcc 60 && \
+#     update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc-9.5.0/bin/g++ 60 && \
+#     update-alternatives --config gcc && \
+#     update-alternatives --config g++
 
-# install glibc
-RUN apt update && apt install -y bison && \
-    mkdir /tmp/glibc && cd /tmp/glibc && \
-    wget https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.xz && \
-    tar -xf glibc-2.29.tar.xz && \
-    cd glibc-2.29 && mkdir build && cd build && \
-    unset LD_LIBRARY_PATH && \
-    ../configure --prefix=/usr/local --disable-sanity-checks && \
-    make -j$(nproc) && make install && \
-    cp /usr/local/lib/libm-2.29.so /lib/x86_64-linux-gnu/ && \
-    ln -sf /lib/x86_64-linux-gnu/libm-2.29.so /lib/x86_64-linux-gnu/libm.so.6 && \
-    rm -rf /tmp/glibc
+# # install glibc
+# RUN apt update && apt install -y bison && \
+#     mkdir /tmp/glibc && cd /tmp/glibc && \
+#     wget https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.xz && \
+#     tar -xf glibc-2.29.tar.xz && \
+#     cd glibc-2.29 && mkdir build && cd build && \
+#     unset LD_LIBRARY_PATH && \
+#     ../configure --prefix=/usr/local --disable-sanity-checks && \
+#     make -j$(nproc) && make install && \
+#     cp /usr/local/lib/libm-2.29.so /lib/x86_64-linux-gnu/ && \
+#     ln -sf /lib/x86_64-linux-gnu/libm-2.29.so /lib/x86_64-linux-gnu/libm.so.6 && \
+#     rm -rf /tmp/glibc
 
-# install python3.9.19
-RUN rm -rf /tmp/py39 && \
-    mkdir -p /tmp/py39 && cd /tmp/py39 && \
-    wget https://www.python.org/ftp/python/3.9.19/Python-3.9.19.tgz && \
-    tar -xzf Python-3.9.19.tgz && \
-    cd Python-3.9.19 && \
-    mkdir build && cd build && \
-    ../configure --prefix=/usr/local --enable-optimizations --with-ensurepip=install && \
-    make -j$(nproc) && make -j$(nproc) install && \
-    ln -sf /usr/local/bin/python3.9 /usr/bin/python3 && \
-    ln -sf /usr/local/bin/python3.9 /usr/bin/python
-
+# # install python3.9.19
+# RUN rm -rf /tmp/py39 && \
+#     mkdir -p /tmp/py39 && cd /tmp/py39 && \
+#     wget https://www.python.org/ftp/python/3.9.19/Python-3.9.19.tgz && \
+#     tar -xzf Python-3.9.19.tgz && \
+#     cd Python-3.9.19 && \
+#     mkdir build && cd build && \
+#     ../configure --prefix=/usr/local --enable-optimizations --with-ensurepip=install && \
+#     make -j$(nproc) && make -j$(nproc) install && \
+#     ln -sf /usr/local/bin/python3.9 /usr/bin/python3 && \
+#     ln -sf /usr/local/bin/python3.9 /usr/bin/python
 # ascend tools
 ARG ASCEND_CANN=8.0.0.alpha003
 RUN mkdir /tmp/ascend_tool && cd /tmp/ascend_tool && \
-    wget -O toolkit.run https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Milan-ASL/Milan-ASL%20V100R001C20SPC703/Ascend-cann-toolkit_${ASCEND_CANN}_linux-${ARCH}.run?response-content-type=application/octet-stream && \
+    wget -O toolkit.run https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Milan-ASL/Milan-ASL%20V100R001C20SPC703/Ascend-cann-toolkit_8.0.0.alpha003_linux-x86_64.run?response-content-type=application/octet-stream && \
     bash toolkit.run --quiet --install --install-path=$ASCEND_BASE --install-for-all --force  && \
-    wget -O kernels.run https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Milan-ASL/Milan-ASL%20V100R001C20SPC703/Ascend-cann-kernels-910b_${ASCEND_CANN}_linux-${ARCH}.run?response-content-type=application/octet-stream && \
+    wget -O kernels.run https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Milan-ASL/Milan-ASL%20V100R001C20SPC703/Ascend-cann-kernels-910b_8.0.0.alpha003_linux-x86_64.run?response-content-type=application/octet-stream && \
     bash kernels.run --quiet --install --install-path=$ASCEND_BASE --install-for-all --force  && \
     rm -rf /tmp/ascend_tool
-ARG TORCH_PACKAGE=2.3.1
-RUN pip3 install --extra-index-url https://download.pytorch.org/whl/cpu/ torch==${TORCH_PACKAGE}
-ARG TORCH_NPU_PACKAGE=https://gitee.com/ascend/pytorch/releases/download/v6.0.rc3-pytorch2.3.1/torch_npu-2.3.1.post2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
-RUN mkdir -p /tmp/torch_npu && cd /tmp/torch_npu && \
-    wget --no-check-certificate ${TORCH_NPU_PACKAGE} && \
-    pip3 install *.whl && \
-    rm /tmp/torch_npu -rf
 
-# pip install torch and torch_npu
-RUN mkdir -p /tmp/torch && cd /tmp/torch && \
-    # . ${PY3_XLLM}/bin/activate && \
-    pip3 uninstall -y torch torch_npu && \
-    wget --no-check-certificate https://download.pytorch.org/whl/cpu/torch-2.3.1%2Bcpu-cp39-cp39-linux_x86_64.whl#sha256=a3cb8e61ba311cee1bb7463cbdcf3ebdfd071e2091e74c5785e3687eb02819f9 && \
-    pip3 install torch-2.3.1+cpu-cp39-cp39-linux_x86_64.whl && \
-    wget --no-check-certificate https://gitee.com/ascend/pytorch/releases/download/v6.0.0-pytorch2.3.1/torch_npu-2.3.1.post4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl && \
-    pip3 install torch_npu-2.3.1.post4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl && \
-    rm /tmp/torch -rf
-# pip install 
-RUN  pip3 install --no-cache-dir pyspark==3.0.1 py4j==0.10.9 ||  pip3 install --no-cache-dir ipython==7.19.0 ipykernel==5.4.3 findspark jupyter_kernel_gateway && \
-    groupadd --non-unique -g 1001 yarn || true && useradd -g 1001 -u 1001 -k /root -m yarn || true && dpkg-reconfigure -f noninteractive tzdata && unset https_proxy http_proxy no_proxy  && echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
-    chgrp root /etc/passwd && chmod ug+rw /etc/passwd && rm -rf /root/.cache 
-    # rm -rf /opt/spark3 && cp -rf /opt/tiger/spark3/spark-stable /opt/spark3 && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/ 
-#  WORKDIR /opt/spark3/work-dir 
-#  RUN chmod g+w /opt/spark3/work-dir 
-# for 
-RUN echo "Cmnd_Alias TIGER_COMMANDS = /usr/bin/svstat, /usr/bin/svc, /etc/init.d/nginx, /usr/bin/uwsgi, /usr/sbin/iotop, /sbin/setcap,/opt/tiger/bin/cgroups_root_util, /usr/sbin/tcpdump, /usr/bin/perf, /bin/echo_oom\ntiger ALL=(ALL) NOPASSWD: TIGER_COMMANDS" > /etc/sudoers.d/tiger
-RUN echo "tiger ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudoers
+# ARG TORCH_PACKAGE=https://download.pytorch.org/whl/cpu/torch-2.3.1%2Bcpu-cp311-cp311-linux_x86_64.whl#sha256=a272defe305dbd944aa28a91cc3db0f0149495b3ebec2e39723a7224fa05dc57
+# # RUN pip3 install torch==2.4.0+cpu  --index-url https://download.pytorch.org/whl/cpu
+# ARG TORCH_NPU_PACKAGE=https://gitee.com/ascend/pytorch/releases/download/v6.0.0-pytorch2.3.1/torch_npu-2.3.1.post4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
+# RUN sudo mkdir /tmp/torch_npu && cd /tmp/torch_npu && \
+#     sudo wget --no-check-certificate ${TORCH_NPU_PACKAGE} && \
+#     sudo wget --no-check-certificate ${TORCH_PACKAGE} && \
+#     sudo pip3 install *.whl && \
+#     sudo rm /tmp/torch_npu -rf
+
+# RUN pip3 install torch-npu==2.3.1
+
+
+# # pip install 
+# RUN  pip3 install --no-cache-dir pyspark==3.0.1 py4j==0.10.9 ||  pip3 install --no-cache-dir ipython==7.19.0 ipykernel==5.4.3 findspark jupyter_kernel_gateway && \
+#     groupadd --non-unique -g 1001 yarn || true && useradd -g 1001 -u 1001 -k /root -m yarn || true && dpkg-reconfigure -f noninteractive tzdata && unset https_proxy http_proxy no_proxy  && echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
+#     chgrp root /etc/passwd && chmod ug+rw /etc/passwd && rm -rf /root/.cache 
+#     # rm -rf /opt/spark3 && cp -rf /opt/tiger/spark3/spark-stable /opt/spark3 && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/ 
+# #  WORKDIR /opt/spark3/work-dir 
+# #  RUN chmod g+w /opt/spark3/work-dir 
+# # for 
+# RUN echo "Cmnd_Alias TIGER_COMMANDS = /usr/bin/svstat, /usr/bin/svc, /etc/init.d/nginx, /usr/bin/uwsgi, /usr/sbin/iotop, /sbin/setcap,/opt/tiger/bin/cgroups_root_util, /usr/sbin/tcpdump, /usr/bin/perf, /bin/echo_oom\ntiger ALL=(ALL) NOPASSWD: TIGER_COMMANDS" > /etc/sudoers.d/tiger
+# RUN echo "tiger ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudoers
 # 设置sshd自启动
 CMD ["/usr/sbin/sshd", "-D"]
 
